name: Node.js CI
on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - run: yarn run build
      - run: yarn semantic-release
